---

Django Tests:
  image: ${DOCKER_REGISTRY}/django:latest
  tags:
    - bear-gitlab-runners
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
  script:
    - cd django
    - mv core/local_settings.test.py core/local_settings.py
    - coverage run manage.py test
    - coverage report

accessibility:
  tags:
  - bear-gitlab-runners
  image: ${DOCKER_REGISTRY}/django:latest
  before_script:
    - pip install -r requirements.txt
  script:
    - cd django
    - mv core/local_settings.test.py core/local_settings.py
    - python manage.py migrate
    - python manage.py runserver & sleep 5
    - pa11y-ci

flake8:
  tags:
  - bear-gitlab-runners
  image: pipelinecomponents/flake8:latest
  script:
    - flake8 -v .

stylelint:
  tags:
  - bear-gitlab-runners
  image: pipelinecomponents/stylelint
  script:
    - stylelint .

eslint:
  tags:
  - bear-gitlab-runners
  image: pipelinecomponents/stylelint
  script:
    # - eslint .
    - echo "Enable eslint when JS added"

tidy:
  tags:
  - bear-gitlab-runners
  image: python:3.6
  before_script:
    - apt update
    - apt -y install tidy
  script:
    # tidy exits 1 for warnings, 2 for errors, 0 for neither.
    - export EX=0; for f in $(find -name *.html); do MYEX=$(tidy $f; echo $?); if [[ ${MYEX} -eq 2 ]]; then EX=$(expr ${EX} + 1); fi; done; if [[ ${EX} -ne 0 ]] ; then exit ${EX}; fi
